name: CI/CD Wisecow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3️⃣ Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow:latest .

    # 4️⃣ Push Docker image
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

    # 5️⃣ Setup kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.4'

    # 6️⃣ Write kubeconfig from GitHub secret
    - name: Setup kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo $KUBECONFIG | base64 --decode > $HOME/.kube/config
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}

    # 7️⃣ Deploy to Kubernetes
    - name: Deploy Wisecow to Kubernetes
      run: |
        kubectl set image deployment/wisecow-deployment wisecow=${{ secrets.DOCKER_USERNAME }}/wisecow:latest
        kubectl rollout status deployment/wisecow-deployment
