name: CI/CD Wisecow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted   # 👈 your VM runner

    steps:
    # 1️⃣hCheckout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ g in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3️⃣ Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow:latest .

    # 4️⃣ Push Docker image
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

    # 5️⃣ Use existing kubeconfig (local VM already has access)
    - name: Use local kubeconfig
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl config current-context

    # 6️⃣ Deploy to Kubernetes
    - name: Deploy Wisecow to Kubernetes
      run: |
        kubectl apply -f ./k8s/*
        kubectl set image deployment/wisecow-deployment wisecow=${{ secrets.DOCKER_USERNAME }}/wisecow:latest
        kubectl rollout status deployment/wisecow-deployment
